# Generated by Django 5.1.7 on 2025-03-17 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('operator_login', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('agent_name', models.CharField(max_length=100, unique=True)),
                ('team', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QAEvaluation',
            fields=[
                ('evaluation_key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('priority', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('interaction_date', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('updated', models.DateTimeField()),
                ('total_final_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_evaluations', to='dashboard.agent')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_evaluations', to='dashboard.agent')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(max_length=50)),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('sessions_cnt', models.IntegerField()),
                ('actions_cnt', models.IntegerField()),
                ('action_close_cnt', models.IntegerField()),
                ('productivity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('AHT_sec', models.IntegerField()),
                ('SL_session_duration', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ratio_close_any', models.DecimalField(decimal_places=2, max_digits=5)),
                ('closed_sessions_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('CSAT_cnt', models.IntegerField()),
                ('CSAT_avg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('worktime_mins', models.IntegerField()),
                ('postcall_avg_sec', models.IntegerField()),
                ('OCC', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operator_login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.agent')),
            ],
            options={
                'unique_together': {('operator_login', 'segment', 'week_start', 'week_end')},
            },
        ),
    ]
