# Generated by Django 5.1.7 on 2025-03-27 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qaevaluation',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_evaluations', to='dashboard.agent', to_field='agent_name'),
        ),
        migrations.AlterField(
            model_name='qaevaluation',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_evaluations', to='dashboard.agent', to_field='agent_name'),
        ),
    ]
