# Generated by Django 5.1.7 on 2025-03-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_qaevaluation_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qaevaluation',
            name='comments_on_interaction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qaevaluation',
            name='ticket',
            field=models.URLField(blank=True, null=True),
        ),
    ]
