# Generated by Django 5.1.7 on 2025-03-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_qaevaluation_comments_on_interaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklymetrics',
            name='AHT_sec',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='weeklymetrics',
            name='CSAT_cnt',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='weeklymetrics',
            name='action_close_cnt',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='weeklymetrics',
            name='actions_cnt',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='weeklymetrics',
            name='postcall_avg_sec',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='weeklymetrics',
            name='sessions_cnt',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='weeklymetrics',
            name='worktime_mins',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
